services:
  configsvr1:
    build: ./config-server
    container_name: configsvr1
    env_file: .env
    environment:
      - REPLICA_SET_NAME=configReplSet
      - INIT_CONFIG=true
    volumes:
      - ./data/configsvr1:/data/configdb

  configsvr2:
    build: ./config-server
    container_name: configsvr2
    env_file: .env
    environment:
      - REPLICA_SET_NAME=configReplSet
    volumes:
      - ./data/configsvr2:/data/configdb

  configsvr3:
    build: ./config-server
    container_name: configsvr3
    env_file: .env
    environment:
      - REPLICA_SET_NAME=configReplSet
    volumes:
      - ./data/configsvr3:/data/configdb

  shard1:
    build: ./shard
    container_name: shard1
    env_file: .env
    environment:
      - REPLICA_SET_NAME=shard1
    volumes:
      - ./data/shard1_db1:/data/db1
      - ./data/shard1_db2:/data/db2
      - ./data/shard1_db3:/data/db3

  shard2:
    build: ./shard
    container_name: shard2
    env_file: .env
    environment:
      - REPLICA_SET_NAME=shard2
    volumes:
      - ./data/shard2_db1:/data/db1
      - ./data/shard2_db2:/data/db2
      - ./data/shard2_db3:/data/db3

  shard3:
    build: ./shard
    container_name: shard3
    env_file: .env
    environment:
      - REPLICA_SET_NAME=shard3
    volumes:
      - ./data/shard3_db1:/data/db1
      - ./data/shard3_db2:/data/db2
      - ./data/shard3_db3:/data/db3

  mongos1:
    build: ./mongos
    container_name: mongos1
    env_file: .env
    environment:
      - REGISTER_SHARDS=true  # для первого mongos
    depends_on:
      - configsvr1
      - configsvr2
      - configsvr3
      - shard1
      - shard2
      - shard3

  mongos2:
    build: ./mongos
    container_name: mongos2
    env_file: .env
    depends_on:
      - configsvr1
      - configsvr2
      - configsvr3
      - shard1
      - shard2
      - shard3

  nginx:
    image: nginx:alpine
    container_name: mongos-loadbalancer
    ports:
      - "27080:27080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mongos1
      - mongos2
